# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-04 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.CharField(max_length=50, verbose_name='项目名称')),
                ('urltype', models.CharField(max_length=50, verbose_name='类型')),
                ('urltestenv', models.CharField(max_length=300, verbose_name='测试环境')),
                ('urlformalenv', models.CharField(max_length=300, verbose_name='正式环境')),
                ('uid', models.IntegerField(verbose_name='用户编号')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户账号')),
                ('password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('isadmin', models.BooleanField(verbose_name='管理员身份')),
            ],
        ),
    ]
